#!/bin/sh
set -eu

lb config \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer false \
  --apt-recommends false \
  --memtest none \
  --bootappend-live "boot=live components quiet splash" \
  --iso-application "SentinelUSB" \
  --iso-publisher "SentinelUSB Project" \
  --iso-volume "SENTINELUSB"
