#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
  --security false \
  --binary-images iso-hybrid \
  --debian-installer false \
  --apt-recommends false \
  --memtest none \
  --bootappend-live "boot=live components quiet splash" \
  --iso-application "SentinelUSB" \
  --iso-publisher "SentinelUSB Project" \
  --iso-volume "SENTINELUSB"
